apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-fe-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: {{ .Values.frontend.ingress.host }} 
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: job-fe-service
                port:
                  number: {{ .Values.frontend.port }} 
          - path: /job
            pathType: Prefix
            backend:
              service:
                name: job-be-service
                port:
                  number: 80 #{{ .Values.backend.port }}