apiVersion: v1
kind: Service
metadata:
  name: job-fe-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.frontend.app }} 
  ports:
    - port: {{ .Values.frontend.port }} 
      targetPort: {{ .Values.frontend.port }} 
