backend:
  image: adamanticfilippo/backend:${BUILD_NUMBER}
  replicas: 2
  port: 5000
  app: job-be

frontend:
  image: adamanticfilippo/frontend:${BUILD_NUMBER}
  replicas: 1
  port: 80
  ingress:
    host: jobexample.adamantic.net
  app: job-fe

database:
  image: adamanticfilippo/postgres:${BUILD_NUMBER}
  replicas: 2
  storage: 8Gi
  username: ps_user
  password: SecurePassword
  dbname: ps_db
  port: "5432"
  app: job-db

