apiVersion: v1
kind: ConfigMap
metadata:
  name: job-be-configmap
  labels:
    app: {{ .Values.backend.app }}
data:
  POSTGRES_USER: {{ .Values.database.username }}
  POSTGRES_PASSWORD: {{ .Values.database.password }}
  POSTGRES_DB: {{ .Values.database.dbname }}
  POSTGRES_HOST: 'global-postgres-postgresql'
  POSTGRES_PORT: "{{ .Values.database.port }}"
