apiVersion: apps/v1
kind: Deployment
metadata:
  name: job-be-deployment
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.backend.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.backend.app }}
    spec:
      containers:
        - name: {{ .Values.backend.app }}
          image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.backend.port }}
          envFrom:
            - configMapRef:
                name: job-be-configmap

