apiVersion: v1
kind: Service
metadata:
  name: job-be-service
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.backend.app }}
  ports:
    - port: 80
      targetPort: {{ .Values.backend.port }}
