apiVersion: v1
kind: Service
metadata:
  name: job-db-service
  labels:
    app: {{ .Values.database.app }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.database.port }}
      targetPort: {{ .Values.database.port }}
  selector:
    app: {{ .Values.database.app }}

