apiVersion: v1
kind: PersistentVolume
metadata:
  name: job-db-pv
  labels:
    type: local
    app: {{ .Values.database.app }}
spec:
  storageClassName: manual
  capacity:
    storage: {{ .Values.database.storage }}
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/postgresql
